### ISSUE TITLE
Bug in appending python3-scipy?

### ISSUE THREAD

**Issue by jhuang2010** [tuxable-ltd/meta-scikit-learn#12]
I have attempted the following zeus build with both meta-scipy and meta-scikit-learn layers included but it failed with the following errors. Renaming python3-scipy_1.3%.bbappend to python3-scipy-native_1.3%.bbappend seemed to fix it. I am not sure what caused the failure in the first place though? 

Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "imx6ul-var-dart"
DISTRO               = "fsl-imx-x11"
DISTRO_VERSION       = "5.4-zeus"
TUNE_FEATURES        = "arm vfp cortexa7 neon thumb callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            = "HEAD:0275e68b0576cdefc19718e4b1977044f9f43f48"
meta-oe              
meta-multimedia      
meta-python          = "HEAD:aad5b3d070cd8c58828b0975cf861d8ebc90f460"
meta-freescale       = "HEAD:0be39721cea6e04c589a419f4bb07fabd0da6704"
meta-freescale-3rdparty = "HEAD:aea3771baa77e74762358ceb673d407e36637e5f"
meta-freescale-distro = "HEAD:ca27d12e4964d1336e662bcc60184bbff526c857"
meta-bsp             
meta-sdk             
meta-ml              = "HEAD:64918e055f82e7c1d622a28856fb7ca1d1b93b47"
meta-browser         = "HEAD:5f365ef0f842ba4651efe88787cf9c63bc8b6cb3"
meta-rust            = "HEAD:5cda04c7c2158fc982502ca1e7893f71e4ca1729"
meta-gnome           
meta-networking      
meta-filesystems     = "HEAD:aad5b3d070cd8c58828b0975cf861d8ebc90f460"
meta-qt5             = "HEAD:432ad2aa6c3a13253fefc909faba368851d21fb1"
meta-swupdate        = "HEAD:8ad6a75e1778cdda671b3d6aea2a9692613020ec"
meta-virtualization  = "HEAD:514ce5f6b240600f06b9956737be1e33900bacac"
meta-variscite-imx   = "HEAD:037ae3cab30fcaeb17d465ff41efcb68c0a21a22"
meta-scipy           = "zeus:757b20376ed7cb8e4497c6b9bdc5444a5b5a4e81"
meta-scikit-learn    = "zeus:d2efaea114efbad76450e130c6c81df50561e565"

Initialising tasks: 100% |#######################################| Time: 0:00:01
Sstate summary: Wanted 8 Found 7 Missed 1 Current 418 (87% match, 99% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
ERROR: python3-scipy-1.3.3-r0 do_package_qa: QA Issue: /usr/lib/python3.7/site-packages/scipy/optimize/_trlib/_trlib.cpython-37m-arm-linux-gnueabi.so contained in package python3-scipy requires libblas.so.3, but no providers found in RDEPENDS_python3-scipy? [file-rdeps]
ERROR: python3-scipy-1.3.3-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /home/jhuang/var-fsl-yocto/build_x11/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/python3-scipy/1.3.3-r0/temp/log.do_package_qa.4163
ERROR: Task (/home/jhuang/var-fsl-yocto/sources/meta-scipy/recipes-devtools/python/python3-scipy_1.3.3.bb:do_package_qa) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1696 tasks of which 1695 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/jhuang/var-fsl-yocto/sources/meta-scipy/recipes-devtools/python/python3-scipy_1.3.3.bb:do_package_qa
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by jackmitch** [comment]
I'm afraid the Zeus branch isn't really supported anymore as it's so old. From the looks of it I would say maybe something else is messing with the blas recipe? It's got `openblas` in the DEPENDS and it's obviously building with it but OE isn't pulling in the library dependency via the linker. You could probably hack around it just by forcing the RDEPENDS as is stated but it's a workaround rather than a fix.
