### ISSUE TITLE
QA issue python3-scipy requires libblas

### ISSUE THREAD

**Issue by chillking2** [tuxable-ltd/meta-scikit-learn#4]
I'm using dunfell and when bitbaking I get an QA issue
```

ERROR: python3-scipy-1.3.3-r0 do_package_qa: QA Issue: /usr/lib/python3.8/site-packages/scipy/integrate/vode.cpython-38-aarch64-linux-gnu.so contained in package python3-scipy requires libblas.so.3()(64bit), but no providers found in RDEPENDS_python3-scipy? [file-rdeps]
ERROR: python3-scipy-1.3.3-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
```

When I'm not including meta-scikit-learn `bitbake python3-scipy` is running without error.

Does anyone know how to proceed here?

**Comment by jackmitch** [comment]
Hi, the Dunfell support was added by another another contributor #3 @srikanth311 as I don't use the Dunfell branch, but I think what has happened is that they have removed the OpenBLAS support from the scikit recipe, but kept the OPTIMIZED_BLAS from the Lapacke so there isn't any blas support present. I would suggest removing the Lapacke bbappend and retrying the build but it is untested from my side I'm afraid.

**Comment by chillking2** [comment]
Hi,
thanks for your tip! 
I followed your suggestion and removed the lapack folder, but i seems it is needed as I now get an error:
```
ERROR: Nothing PROVIDES 'lapack-native' (but ~/var-fslc-yocto/sources/meta-scikit-learn/recipes-devtools/python/python3-scipy-native_1.5.3.bb DEPENDS on or otherwise requires it). Close matches:
```
Any idea how I can proceed?

**Comment by jackmitch** [comment]
Looks like you still need a couple of lines from that file, I would change it to

https://github.com/tuxable-ltd/meta-scikit-learn/blob/dunfell/recipes-devtools/lapack/lapack_%25.bbappend

```
DEPENDS_remove_class-native = "libgfortran"
BBCLASSEXTEND = "native"
```

**Comment by chillking2** [comment]
I commented the other lines out to only have to two lines you suggested, now it has problems that libblas is build by both openblas and lapack as shown bellow
```
ERROR: python3-scipy-native-1.5.3-r0 do_prepare_recipe_sysroot: The file /usr/lib/libblas.so.3 is installed by both openblas-native and lapack-native, aborting
ERROR: Logfile of failure stored in: ~/var-fslc-yocto/build_xwayland/tmp/work/x86_64-linux/python3-scipy-native/1.5.3-r0/temp/log.do_prepare_recipe_sysroot.118424
ERROR: Task (~/var-fslc-yocto/sources/meta-scikit-learn/recipes-devtools/python/python3-scipy-native_1.5.3.bb:do_prepare_recipe_sysroot) failed with exit code '1'
```
I'm not sure how to resolve this because I cannot find any recipes for lapack-native or openblas-native.

**Comment by jackmitch** [comment]
yeah, I don't know why the layer was so heavily fiddled with to create a dunfell branch, have you tried the Gatesgarth branch on Dunfell? I could see these issues when I merged the branch but I assumed it had been tested to at least some degree although that seems not to be the case.

**Comment by jackmitch** [comment]
https://github.com/tuxable-ltd/meta-scikit-learn/commit/b5ee092c410efa4a20931b5f0d1450a5cf872f58

**Comment by chillking2** [comment]
okay, I try and error a bit with Gatesgarth branch.
I copied python3-pybind11_%.bbappend and python3-scipy_1.5.3.bb from the dunfell branch to it. 
in python3-scikit-learn_0.24.1.bb I changed the path from python3.9 to python3.8 as I only have 3.8. 
`bitbake python3-scikit-learn` was successful, I'm now building my image and give it a quick shot.

**Comment by chillking2** [comment]
image building worked and I can 'import sklearn' successfully on target. 
When I try my code I'm running into an AttributeError, but I guess that could also occure because I trained and pickled the classifier using scikit-learn-0.22.
Big thank you for your help @jackmitch !

**Comment by abhishekwalia33** [comment]
hi i am facing error in porting python3-scikit-leran on riscv64 target
if anybody did this please share to me ,thanks in advance


ERROR: python3-scipy-1.5.3-r0 do_prepare_recipe_sysroot: The file /usr/include/cblas.h is installed by both openblas and lapack, aborting
ERROR: Logfile of failure stored in: /home/abhishek/exaleap/sources/fu540-build/tmp-glibc/work/riscv64-oe-linux/python3-scipy/1.5.3-r0/temp/log.do_prepare_recipe_sysroot.7159
ERROR: Task (/home/abhishek/exaleap/sources/meta-scipy/recipes-devtools/python/python3-scipy_1.5.3.bb:do_prepare_recipe_sysroot) failed with exit code '1'
[](url)](url)

**Comment by abhishekwalia33** [comment]
hi i am facing error in porting python3-scikit-learn on riscv64 target
if anybody did this please share to me ,thanks in advance

ERROR: python3-scipy-1.5.3-r0 do_prepare_recipe_sysroot: The file /usr/include/cblas.h is installed by both openblas and lapack, aborting
ERROR: Logfile of failure stored in: /home/abhishek/exaleap/sources/fu540-build/tmp-glibc/work/riscv64-oe-linux/python3-scipy/1.5.3-r0/temp/log.do_prepare_recipe_sysroot.7159
ERROR: Task (/home/abhishek/exaleap/sources/meta-scipy/recipes-devtools/python/python3-scipy_1.5.3.bb:do_prepare_recipe_sysroot) failed with exit code '1'
](url)
