### ISSUE TITLE
Compatibility with Zeus

### ISSUE THREAD

**Issue by ricbrue** [tuxable-ltd/meta-scikit-learn#5]
Is it possible to use this layer with the Zeus version? Thank you.

**Comment by jackmitch** [comment]
Hi @ricbrue, there were issues porting it to Dunfell so in it's current form no. You may be able to backport it to Zeus with an updated Numpy, but I doubt it will be simple. Zeus is EOL now, so I would suggest moving your build to Dunfell at a minimum and as a bonus that is also an LTS release.
